"""Generate migrations/0003_core.sql from src/0003_core_tables.sql.

Appends, for every core_* table, the receipt-first trigger and the
append-only triggers. Deterministic: same input bytes, same output bytes.
"""
import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parent.parent
src = (root / "src" / "0003_core_tables.sql").read_text(encoding="utf-8")

tables = []
for m in re.finditer(r"CREATE TABLE (core_\w+) \(\n  (\w+)\s+INTEGER PRIMARY KEY", src):
    tables.append((m.group(1), m.group(2)))

skip_receipt = {"core_blocker_state_vocab"}
out = [src.rstrip("\n"), "",
       "------------------------------------------------------------------------------",
       "-- Generated by tools/gen_0003.py: receipt-first and append-only triggers",
       "------------------------------------------------------------------------------", ""]
for table, pk in tables:
    if table in skip_receipt:
        continue
    out.append(f"""CREATE TRIGGER {table}_receipt_first BEFORE INSERT ON {table}
WHEN NEW.{pk} IS NULL
  OR NOT EXISTS (SELECT 1 FROM meta_receipt r
                 WHERE r.receipt_id = NEW.receipt_id AND r.table_name = '{table}'
                   AND r.row_pk = NEW.{pk} AND r.op = 'INSERT')
BEGIN SELECT RAISE(ABORT, '{table}: explicit key and a prior matching receipt are required'); END;""")
alltables = [t for t, _ in tables] + ["core_blocker_state_vocab"]
for table in alltables:
    out.append(f"CREATE TRIGGER {table}_no_update BEFORE UPDATE ON {table} BEGIN SELECT RAISE(ABORT, '{table} is append-only'); END;")
    out.append(f"CREATE TRIGGER {table}_no_delete BEFORE DELETE ON {table} BEGIN SELECT RAISE(ABORT, '{table} is append-only'); END;")
text = "\n".join(out) + "\n"
(root / "migrations" / "0003_core.sql").write_text(text, encoding="utf-8")
print(len(tables), "tables")
