"""Generate unsilo/migrations/*.sql from unsilo/schema_src/*.sql.

Each output = the hand-written source + generated triggers for every receipted
table that source creates (any stg_/core_/ev_ table with a receipt_id column):
  <t>_receipt_image  the row must equal its receipt's after-image, column by
                     column, with no extra keys (receipt-first, one write path)
  <t>_no_update      append-only
  <t>_no_delete      append-only
Deterministic: same sources, same bytes. tests/test_migrations.py fails if the
committed migrations differ from a fresh generation.

Usage: python tools/gen_migrations.py [--check]
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from unsilo import db  # noqa: E402

SRC = ROOT / "unsilo" / "schema_src"
OUT = ROOT / "unsilo" / "migrations"
MARK = "\n-- ---------------------------------------------------------------------------\n" \
       "-- GENERATED by tools/gen_migrations.py: receipt-image equality + append-only.\n" \
       "-- Do not edit below this line; edit unsilo/schema_src and regenerate.\n" \
       "-- ---------------------------------------------------------------------------\n"


def receipted_tables(conn):
    out = []
    for (name,) in conn.execute("SELECT name FROM sqlite_schema WHERE type = 'table' ORDER BY name").fetchall():
        if not (name.startswith(("core_", "stg_", "ev_"))):
            continue
        info = conn.execute(f"PRAGMA table_info({name})").fetchall()
        cols = [r[1] for r in info]
        if "receipt_id" not in cols:
            continue
        pks = [r[1] for r in info if r[5] == 1]
        if len(pks) != 1:
            raise SystemExit(f"{name}: receipted tables need one INTEGER PRIMARY KEY")
        out.append((name, pks[0], cols))
    return out


def triggers(name, pk, cols):
    keys = ", ".join(f"'{c}'" for c in cols)
    eq = "\n    AND ".join(f"json_extract(r.after_image_json, '$.{c}') IS NEW.{c}" for c in cols)
    return (
        f"CREATE TRIGGER {name}_receipt_image BEFORE INSERT ON {name}\n"
        f"WHEN NOT EXISTS (SELECT 1 FROM meta_receipt r\n"
        f"  WHERE r.receipt_id = NEW.receipt_id AND r.table_name = '{name}' AND r.row_pk = NEW.{pk} AND r.op = 'INSERT'\n"
        f"    AND (SELECT count(*) FROM json_each(r.after_image_json)) = {len(cols)}\n"
        f"    AND NOT EXISTS (SELECT 1 FROM json_each(r.after_image_json) j WHERE j.key NOT IN ({keys}))\n"
        f"    AND {eq})\n"
        f"BEGIN SELECT RAISE(ABORT, '{name}: row must equal its receipt after-image'); END;\n"
        f"CREATE TRIGGER {name}_no_update BEFORE UPDATE ON {name}\n"
        f"BEGIN SELECT RAISE(ABORT, '{name} is append-only'); END;\n"
        f"CREATE TRIGGER {name}_no_delete BEFORE DELETE ON {name}\n"
        f"BEGIN SELECT RAISE(ABORT, '{name} is append-only'); END;\n"
    )


def generate():
    conn = db.connect(":memory:")
    seen = set()
    outputs = {}
    for src in sorted(SRC.glob("*.sql")):
        body = src.read_text(encoding="utf-8")
        conn.execute(body).fetchall()
        new = [t for t in receipted_tables(conn) if t[0] not in seen]
        gen = "".join(triggers(*t) for t in new)
        seen.update(t[0] for t in new)
        text = body.rstrip("\n") + "\n" + (MARK + gen if gen else "")
        conn.execute(gen).fetchall()
        outputs[src.name] = text.encode("utf-8")
    return outputs


def main():
    check = "--check" in sys.argv
    outputs = generate()
    bad = []
    for name, data in outputs.items():
        p = OUT / name
        if check:
            if not p.exists() or p.read_bytes() != data:
                bad.append(name)
        else:
            OUT.mkdir(exist_ok=True)
            p.write_bytes(data)
    extra = sorted({p.name for p in OUT.glob("*.sql")} - set(outputs))
    if check and (bad or extra):
        raise SystemExit(f"migrations out of date: {bad} extra: {extra}")
    print("ok" if check else f"wrote {len(outputs)} migrations")


if __name__ == "__main__":
    main()
